# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/0.7.1/tag_publish/schema.json

pypi:
  versions:
    - version_tag
    - version_branch
  packages:
    - {}
docker:
  auto_login: true
  images:
    - name: camptocamp/tag-publish
helm:
  packages:
    - folder: tests
node:
  packages:
    - folder: tests
dispatch:
  - {}
