# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/master/tag_publish/schema.json

pypi:
  versions:
    - version_tag
    - version_branch
  packages:
    - path: .
docker:
  images:
    - name: camptocamp/tag-publish
