exclude: |-
  (?x)^(
    tag_publish/configuration\.py
  )$

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.4
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/camptocamp/jsonschema-gentypes
    rev: 2.10.0
    hooks:
      - id: jsonschema-gentypes
        files: |-
          (?x)(
            ^ĵsonschema-gentypes.yaml$
            |^tag_publish/schema.json$
          )
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 1.0.0
    hooks:
      - id: jsonschema-validator
        files: |-
          (?x)^(
            \.github/ghci\.yaml
            |\.github/publish\.yaml
            |jsonschema\-gentypes\.yaml
          )$
  - repo: https://github.com/sbrunner/jsonschema2md2
    rev: 1.5.2
    hooks:
      - id: jsonschema2md
        files: tag_publish/schema.json
        args:
          - --pre-commit
          - tag_publish/schema.json
          - config.md
  - repo: https://github.com/sbrunner/hooks
    rev: 1.4.0
    hooks:
      - id: copyright
      - id: poetry2-lock
        additional_dependencies:
          - poetry==2.1.2 # pypi
      - id: canonicalize
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: |-
          (?x)(
            (.*/)?poetry\.lock$
          )
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 40.30.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.9
    hooks:
      - id: ripsecrets
  - repo: https://github.com/PyCQA/prospector
    rev: v1.15.2
    hooks:
      - id: prospector
        args:
          - --profile=utils:pre-commit
          - --die-on-tool-error
          - --output-format=pylint
          - --profile=.prospector.yaml
        additional_dependencies:
          - prospector-profile-duplicated==1.10.4 # pypi
          - prospector-profile-utils==1.21.9 # pypi
          - pylint[spelling]==3.3.6 # pypi
          - ruff==0.9.9 # pypi
        exclude: |-
          (?x)(
            ^tests?/?
            |/tests?(/|$)
            |.*/tests(/|$)
            |(^|/)test_[_a-zA-Z0-9]+.py$
            |(^|/)[_a-zA-Z0-9]+_tests?.py$
            |(^|/)tests?.py$
          )
      - id: prospector
        args:
          - --die-on-tool-error
          - --output-format=pylint
          - --profile=utils:tests
          - --profile=utils:pre-commit
        additional_dependencies:
          - prospector-profile-utils==1.21.9 # pypi
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff-format
  - repo: https://github.com/mheap/json-schema-spell-checker
    rev: main
    hooks:
      - id: json-schema-spell-checker
        files: |-
          (?x)^(
            tag_publish/schema\.json
          )$
        args:
          - --fields=description
          - --spelling=.github/spell-ignore-words.txt
          - --ignore-numbers
          - --ignore-acronyms
          - --en-us
  - repo: https://github.com/sbrunner/python-versions-hook
    rev: 1.0.0
    hooks:
      - id: python-versions
